# Generated by Django 6.0.4 on 2026-04-19 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Букет атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('tags', models.CharField(blank=True, help_text='Үтір арқылы жазыңыз: роза, қызыл, сыйлық', max_length=500)),
                ('category', models.CharField(choices=[('mono', 'Моно-букеттер'), ('premium', 'Премиум'), ('box', 'Қораптағы гүлдер')], max_length=50, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Бағасы (₸)')),
                ('image_url', models.URLField(max_length=500, verbose_name='Сурет сілтемесі')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеттер',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Профиль суреті')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
